// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYWkCTZJjHnt9otkAVc5ZZJoeMnPCdWlU',
    appId: '1:137376147306:web:900fb6d5ffb8090cde2713',
    messagingSenderId: '137376147306',
    projectId: 'car-rental-app-4befc',
    authDomain: 'car-rental-app-4befc.firebaseapp.com',
    storageBucket: 'car-rental-app-4befc.appspot.com',
    measurementId: 'G-S56286YLKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQEy-FJ4P0N-RRKIaYP4sa-pxolr18-bc',
    appId: '1:137376147306:android:f147ee399716f617de2713',
    messagingSenderId: '137376147306',
    projectId: 'car-rental-app-4befc',
    storageBucket: 'car-rental-app-4befc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg587g7fmSF54ud85skPunvyPt0NTqtOU',
    appId: '1:137376147306:ios:6cf9285df7513370de2713',
    messagingSenderId: '137376147306',
    projectId: 'car-rental-app-4befc',
    storageBucket: 'car-rental-app-4befc.appspot.com',
    iosClientId: '137376147306-bt1r19802l60j3r5s1favb471un4rver.apps.googleusercontent.com',
    iosBundleId: 'com.dream.vehicle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg587g7fmSF54ud85skPunvyPt0NTqtOU',
    appId: '1:137376147306:ios:552c7591c4d27d6ade2713',
    messagingSenderId: '137376147306',
    projectId: 'car-rental-app-4befc',
    storageBucket: 'car-rental-app-4befc.appspot.com',
    iosClientId: '137376147306-jpiljsa4jfuul3cfa0238ku9qbbp2s3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYWkCTZJjHnt9otkAVc5ZZJoeMnPCdWlU',
    appId: '1:137376147306:web:61ab22c4534ec196de2713',
    messagingSenderId: '137376147306',
    projectId: 'car-rental-app-4befc',
    authDomain: 'car-rental-app-4befc.firebaseapp.com',
    storageBucket: 'car-rental-app-4befc.appspot.com',
    measurementId: 'G-JQPG42LMG4',
  );
}
